package com.keystone.deliverableservice.ENUM;

public enum Permissions {
//	user
	CREATE_USER,UPDATE_USER,DELETE_USER,VIEW_USER,
//customer
	CREATE_CUSTOMER, UPDATE_CUSTOMER,DELETE_CUSTOMER,VIEW_CUSTOMER,
//curior service
	CREATE_SITE,UPDATE_SITE,DELETE_SITE, VIEW_SITE,
//work order
	CREATE_WORK_ORDER,UPDATE_WORK_ORDER,DELETE_WORK_ORDER,VIEW_WORK_ORDER,ASSIGN_WORK_ORDER,CLOSE_WORK_ORDER,CANCEL_WORK_ORDER,
//technician
	START_WORK, HOLD_WORK,RESUME_WORK, COMPLETE_WORK,
//customer
	RAISE_REQUEST,VIEW_REQUEST,
//parts
	ADD_PARTS,UPDATE_PARTS,DELETE_PARTS,VIEW_PARTS,USE_PARTS,
//clock timing
	ADD_TIME_LOGS,VIEW_TIME_LOGS,
//NOTIFICATION
	SEND_NOTIFICATION,
	VIEW_DASHBOARD,VIEW_REPORTS
	
	
}
